# PlatformIO pre-build: gzip webapp/index.html -> include/web/webapp_gz.h
# Wired via extra_scripts = pre:scripts/build_webapp.py

Import("env")

import gzip
from pathlib import Path

ROOT = Path(env.subst("$PROJECT_DIR"))
SRC = ROOT / "webapp" / "index.html"
OUT = ROOT / "include" / "web" / "webapp_gz.h"


def build_webapp(*_args, **_kwargs):
    raw = SRC.read_bytes()
    # mtime=0 keeps the output byte-stable across builds (default varies by
    # Python version; None embeds wall-clock time and dirties the committed header)
    gz = gzip.compress(raw, compresslevel=9, mtime=0)
    # Pin the gzip header's OS byte too: Python 3.14 changed the default from
    # 0x03 (Unix) to 0xFF (unknown), which made the committed header
    # non-byte-stable across Python versions on its own (repo landmine #6
    # requires regenerating from a clean tree to produce an empty git diff).
    gz = bytearray(gz)
    gz[9] = 0xFF
    lines = [
        "// Generated by scripts/build_webapp.py -- do not edit.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <pgmspace.h>",
        "",
        "namespace web {",
        "",
        f"constexpr size_t kWebAppRawLen = {len(raw)};",
        f"constexpr size_t kWebAppGzLen = {len(gz)};",
        "",
        "const unsigned char kWebAppGz[] PROGMEM = {",
    ]
    for i in range(0, len(gz), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in gz[i:i + 16])
        lines.append(f"  {chunk},")
    lines += ["};", "", "}  // namespace web", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"build_webapp: {len(raw)} B -> {len(gz)} B gz -> {OUT.name}")


build_webapp()
