// Generated by scripts/build_region_map.py -- do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace ui::radar {

enum class MapLayer : uint8_t {
  kHighway = 0,
  kWater = 1,
  kBoundary = 2,
  kTown = 3,
};

/** One polyline: [start, start+len) into kMapVerts, tagged by layer. */
struct MapSpan {
  uint16_t start;
  uint16_t len;
  uint8_t layer;
};

/** int16 lat/lon offset from the baked center, in kMapQuantDeg units. */
struct MapVert {
  int16_t dlat;
  int16_t dlon;
};

struct MapTown {
  int16_t dlat;
  int16_t dlon;
  char label[5];
};

constexpr float kMapQuantDeg = 1e-4f;
constexpr float kMapCenterLat = 36.0999f;
constexpr float kMapCenterLon = -80.2442f;
constexpr size_t kMapVertCount = 7752;
constexpr size_t kMapSpanCount = 666;
constexpr size_t kMapTownCount = 36;

extern const MapVert kMapVerts[];
extern const MapSpan kMapSpans[];
extern const MapTown kMapTowns[];

}  // namespace ui::radar
